var annotated_dup =
[
    [ "Gwk", null, [
      [ "Controls", null, [
        [ "Internal", null, [
          [ "ColorButton", "class_gwk_1_1_controls_1_1_internal_1_1_color_button.html", null ]
        ] ],
        [ "Layout", null, [
          [ "CalcPosition", "class_gwk_1_1_controls_1_1_layout_1_1_calc_position.html", "class_gwk_1_1_controls_1_1_layout_1_1_calc_position" ],
          [ "Center", "class_gwk_1_1_controls_1_1_layout_1_1_center.html", null ],
          [ "Table", "class_gwk_1_1_controls_1_1_layout_1_1_table.html", "class_gwk_1_1_controls_1_1_layout_1_1_table" ],
          [ "TableRow", "class_gwk_1_1_controls_1_1_layout_1_1_table_row.html", "class_gwk_1_1_controls_1_1_layout_1_1_table_row" ],
          [ "Tile", "class_gwk_1_1_controls_1_1_layout_1_1_tile.html", "class_gwk_1_1_controls_1_1_layout_1_1_tile" ]
        ] ],
        [ "Property", null, [
          [ "Base", "class_gwk_1_1_controls_1_1_property_1_1_base.html", "class_gwk_1_1_controls_1_1_property_1_1_base" ],
          [ "Checkbox", "class_gwk_1_1_controls_1_1_property_1_1_checkbox.html", "class_gwk_1_1_controls_1_1_property_1_1_checkbox" ],
          [ "ColorSelector", "class_gwk_1_1_controls_1_1_property_1_1_color_selector.html", null ],
          [ "ComboBox", "class_gwk_1_1_controls_1_1_property_1_1_combo_box.html", "class_gwk_1_1_controls_1_1_property_1_1_combo_box" ],
          [ "File", "class_gwk_1_1_controls_1_1_property_1_1_file.html", null ],
          [ "Folder", "class_gwk_1_1_controls_1_1_property_1_1_folder.html", null ],
          [ "Text", "class_gwk_1_1_controls_1_1_property_1_1_text.html", "class_gwk_1_1_controls_1_1_property_1_1_text" ]
        ] ],
        [ "Base", "class_gwk_1_1_controls_1_1_base.html", "class_gwk_1_1_controls_1_1_base" ],
        [ "BaseScrollBar", "class_gwk_1_1_controls_1_1_base_scroll_bar.html", "class_gwk_1_1_controls_1_1_base_scroll_bar" ],
        [ "Button", "class_gwk_1_1_controls_1_1_button.html", "class_gwk_1_1_controls_1_1_button" ],
        [ "Canvas", "class_gwk_1_1_controls_1_1_canvas.html", "class_gwk_1_1_controls_1_1_canvas" ],
        [ "CheckBox", "class_gwk_1_1_controls_1_1_check_box.html", "class_gwk_1_1_controls_1_1_check_box" ],
        [ "CheckBoxWithLabel", "class_gwk_1_1_controls_1_1_check_box_with_label.html", "class_gwk_1_1_controls_1_1_check_box_with_label" ],
        [ "CollapsibleCategory", "class_gwk_1_1_controls_1_1_collapsible_category.html", "class_gwk_1_1_controls_1_1_collapsible_category" ],
        [ "CollapsibleList", "class_gwk_1_1_controls_1_1_collapsible_list.html", "class_gwk_1_1_controls_1_1_collapsible_list" ],
        [ "ColorLerpBox", "class_gwk_1_1_controls_1_1_color_lerp_box.html", "class_gwk_1_1_controls_1_1_color_lerp_box" ],
        [ "ColorPicker", "class_gwk_1_1_controls_1_1_color_picker.html", "class_gwk_1_1_controls_1_1_color_picker" ],
        [ "ColorSlider", "class_gwk_1_1_controls_1_1_color_slider.html", "class_gwk_1_1_controls_1_1_color_slider" ],
        [ "ComboBox", "class_gwk_1_1_controls_1_1_combo_box.html", "class_gwk_1_1_controls_1_1_combo_box" ],
        [ "CrossSplitter", "class_gwk_1_1_controls_1_1_cross_splitter.html", "class_gwk_1_1_controls_1_1_cross_splitter" ],
        [ "DockBase", "class_gwk_1_1_controls_1_1_dock_base.html", "class_gwk_1_1_controls_1_1_dock_base" ],
        [ "DockedTabControl", "class_gwk_1_1_controls_1_1_docked_tab_control.html", "class_gwk_1_1_controls_1_1_docked_tab_control" ],
        [ "FieldLabel", "class_gwk_1_1_controls_1_1_field_label.html", "class_gwk_1_1_controls_1_1_field_label" ],
        [ "FilePicker", "class_gwk_1_1_controls_1_1_file_picker.html", "class_gwk_1_1_controls_1_1_file_picker" ],
        [ "FolderPicker", "class_gwk_1_1_controls_1_1_folder_picker.html", "class_gwk_1_1_controls_1_1_folder_picker" ],
        [ "GroupBox", "class_gwk_1_1_controls_1_1_group_box.html", "class_gwk_1_1_controls_1_1_group_box" ],
        [ "HorizontalScrollBar", "class_gwk_1_1_controls_1_1_horizontal_scroll_bar.html", "class_gwk_1_1_controls_1_1_horizontal_scroll_bar" ],
        [ "HorizontalSlider", "class_gwk_1_1_controls_1_1_horizontal_slider.html", null ],
        [ "HSVColorPicker", "class_gwk_1_1_controls_1_1_h_s_v_color_picker.html", "class_gwk_1_1_controls_1_1_h_s_v_color_picker" ],
        [ "ImagePanel", "class_gwk_1_1_controls_1_1_image_panel.html", "class_gwk_1_1_controls_1_1_image_panel" ],
        [ "Label", "class_gwk_1_1_controls_1_1_label.html", "class_gwk_1_1_controls_1_1_label" ],
        [ "LabelClickable", "class_gwk_1_1_controls_1_1_label_clickable.html", "class_gwk_1_1_controls_1_1_label_clickable" ],
        [ "LabeledRadioButton", "class_gwk_1_1_controls_1_1_labeled_radio_button.html", "class_gwk_1_1_controls_1_1_labeled_radio_button" ],
        [ "ListBox", "class_gwk_1_1_controls_1_1_list_box.html", "class_gwk_1_1_controls_1_1_list_box" ],
        [ "Menu", "class_gwk_1_1_controls_1_1_menu.html", "class_gwk_1_1_controls_1_1_menu" ],
        [ "MenuDivider", "class_gwk_1_1_controls_1_1_menu_divider.html", "class_gwk_1_1_controls_1_1_menu_divider" ],
        [ "MenuItem", "class_gwk_1_1_controls_1_1_menu_item.html", "class_gwk_1_1_controls_1_1_menu_item" ],
        [ "MenuStrip", "class_gwk_1_1_controls_1_1_menu_strip.html", "class_gwk_1_1_controls_1_1_menu_strip" ],
        [ "NumericUpDown", "class_gwk_1_1_controls_1_1_numeric_up_down.html", "class_gwk_1_1_controls_1_1_numeric_up_down" ],
        [ "NumericUpDownButton_Down", "class_gwk_1_1_controls_1_1_numeric_up_down_button___down.html", null ],
        [ "NumericUpDownButton_Up", "class_gwk_1_1_controls_1_1_numeric_up_down_button___up.html", null ],
        [ "PageControl", "class_gwk_1_1_controls_1_1_page_control.html", "class_gwk_1_1_controls_1_1_page_control" ],
        [ "PasswordTextBox", "class_gwk_1_1_controls_1_1_password_text_box.html", "class_gwk_1_1_controls_1_1_password_text_box" ],
        [ "ProgressBar", "class_gwk_1_1_controls_1_1_progress_bar.html", "class_gwk_1_1_controls_1_1_progress_bar" ],
        [ "Properties", "class_gwk_1_1_controls_1_1_properties.html", "class_gwk_1_1_controls_1_1_properties" ],
        [ "PropertyRow", "class_gwk_1_1_controls_1_1_property_row.html", "class_gwk_1_1_controls_1_1_property_row" ],
        [ "PropertyTree", "class_gwk_1_1_controls_1_1_property_tree.html", "class_gwk_1_1_controls_1_1_property_tree" ],
        [ "PropertyTreeNode", "class_gwk_1_1_controls_1_1_property_tree_node.html", "class_gwk_1_1_controls_1_1_property_tree_node" ],
        [ "RadioButton", "class_gwk_1_1_controls_1_1_radio_button.html", null ],
        [ "RadioButtonController", "class_gwk_1_1_controls_1_1_radio_button_controller.html", "class_gwk_1_1_controls_1_1_radio_button_controller" ],
        [ "Rectangle", "class_gwk_1_1_controls_1_1_rectangle.html", "class_gwk_1_1_controls_1_1_rectangle" ],
        [ "ResizableControl", "class_gwk_1_1_controls_1_1_resizable_control.html", "class_gwk_1_1_controls_1_1_resizable_control" ],
        [ "RichLabel", "class_gwk_1_1_controls_1_1_rich_label.html", "class_gwk_1_1_controls_1_1_rich_label" ],
        [ "ScrollControl", "class_gwk_1_1_controls_1_1_scroll_control.html", "class_gwk_1_1_controls_1_1_scroll_control" ],
        [ "Slider", "class_gwk_1_1_controls_1_1_slider.html", "class_gwk_1_1_controls_1_1_slider" ],
        [ "SplitterBar", "class_gwk_1_1_controls_1_1_splitter_bar.html", "class_gwk_1_1_controls_1_1_splitter_bar" ],
        [ "SplitterHorizontal", "class_gwk_1_1_controls_1_1_splitter_horizontal.html", null ],
        [ "SplitterVertical", "class_gwk_1_1_controls_1_1_splitter_vertical.html", "class_gwk_1_1_controls_1_1_splitter_vertical" ],
        [ "StatusBar", "class_gwk_1_1_controls_1_1_status_bar.html", "class_gwk_1_1_controls_1_1_status_bar" ],
        [ "TabButton", "class_gwk_1_1_controls_1_1_tab_button.html", "class_gwk_1_1_controls_1_1_tab_button" ],
        [ "TabControl", "class_gwk_1_1_controls_1_1_tab_control.html", null ],
        [ "TabStrip", "class_gwk_1_1_controls_1_1_tab_strip.html", "class_gwk_1_1_controls_1_1_tab_strip" ],
        [ "TabTitleBar", "class_gwk_1_1_controls_1_1_tab_title_bar.html", "class_gwk_1_1_controls_1_1_tab_title_bar" ],
        [ "TextBox", "class_gwk_1_1_controls_1_1_text_box.html", "class_gwk_1_1_controls_1_1_text_box" ],
        [ "TextBoxMultiline", "class_gwk_1_1_controls_1_1_text_box_multiline.html", "class_gwk_1_1_controls_1_1_text_box_multiline" ],
        [ "TextBoxNumeric", "class_gwk_1_1_controls_1_1_text_box_numeric.html", "class_gwk_1_1_controls_1_1_text_box_numeric" ],
        [ "ToolBarButton", "class_gwk_1_1_controls_1_1_tool_bar_button.html", null ],
        [ "ToolBarStrip", "class_gwk_1_1_controls_1_1_tool_bar_strip.html", null ],
        [ "TreeControl", "class_gwk_1_1_controls_1_1_tree_control.html", "class_gwk_1_1_controls_1_1_tree_control" ],
        [ "TreeNode", "class_gwk_1_1_controls_1_1_tree_node.html", "class_gwk_1_1_controls_1_1_tree_node" ],
        [ "VerticalScrollBar", "class_gwk_1_1_controls_1_1_vertical_scroll_bar.html", null ],
        [ "VerticalSlider", "class_gwk_1_1_controls_1_1_vertical_slider.html", null ],
        [ "WindowCanvas", "class_gwk_1_1_controls_1_1_window_canvas.html", "class_gwk_1_1_controls_1_1_window_canvas" ],
        [ "WindowCloseButton", "class_gwk_1_1_controls_1_1_window_close_button.html", "class_gwk_1_1_controls_1_1_window_close_button" ],
        [ "WindowControl", "class_gwk_1_1_controls_1_1_window_control.html", "class_gwk_1_1_controls_1_1_window_control" ],
        [ "WindowMaximizeButton", "class_gwk_1_1_controls_1_1_window_maximize_button.html", "class_gwk_1_1_controls_1_1_window_maximize_button" ],
        [ "WindowMinimizeButton", "class_gwk_1_1_controls_1_1_window_minimize_button.html", null ]
      ] ],
      [ "ControlsInternal", null, [
        [ "ColorDisplay", "class_gwk_1_1_controls_internal_1_1_color_display.html", "class_gwk_1_1_controls_internal_1_1_color_display" ],
        [ "Dragger", "class_gwk_1_1_controls_internal_1_1_dragger.html", "class_gwk_1_1_controls_internal_1_1_dragger" ],
        [ "Highlight", "class_gwk_1_1_controls_internal_1_1_highlight.html", "class_gwk_1_1_controls_internal_1_1_highlight" ],
        [ "Modal", "class_gwk_1_1_controls_internal_1_1_modal.html", null ],
        [ "Resizer", "class_gwk_1_1_controls_internal_1_1_resizer.html", "class_gwk_1_1_controls_internal_1_1_resizer" ],
        [ "ScrollBarBar", "class_gwk_1_1_controls_internal_1_1_scroll_bar_bar.html", "class_gwk_1_1_controls_internal_1_1_scroll_bar_bar" ],
        [ "ScrollBarButton", "class_gwk_1_1_controls_internal_1_1_scroll_bar_button.html", "class_gwk_1_1_controls_internal_1_1_scroll_bar_button" ],
        [ "SliderBar", "class_gwk_1_1_controls_internal_1_1_slider_bar.html", "class_gwk_1_1_controls_internal_1_1_slider_bar" ],
        [ "Text", "class_gwk_1_1_controls_internal_1_1_text.html", "class_gwk_1_1_controls_internal_1_1_text" ]
      ] ],
      [ "DragAndDrop", null, [
        [ "Package", "struct_gwk_1_1_drag_and_drop_1_1_package.html", "struct_gwk_1_1_drag_and_drop_1_1_package" ]
      ] ],
      [ "Event", null, [
        [ "Caller", "class_gwk_1_1_event_1_1_caller.html", "class_gwk_1_1_event_1_1_caller" ],
        [ "Handler", "class_gwk_1_1_event_1_1_handler.html", "class_gwk_1_1_event_1_1_handler" ],
        [ "Information", "struct_gwk_1_1_event_1_1_information.html", "struct_gwk_1_1_event_1_1_information" ],
        [ "Packet", "struct_gwk_1_1_event_1_1_packet.html", "struct_gwk_1_1_event_1_1_packet" ]
      ] ],
      [ "Hook", null, [
        [ "BaseHook", "class_gwk_1_1_hook_1_1_base_hook.html", "class_gwk_1_1_hook_1_1_base_hook" ]
      ] ],
      [ "Input", null, [
        [ "Allegro", "class_gwk_1_1_input_1_1_allegro.html", "class_gwk_1_1_input_1_1_allegro" ],
        [ "GLFW", "class_gwk_1_1_input_1_1_g_l_f_w.html", "class_gwk_1_1_input_1_1_g_l_f_w" ],
        [ "Null", "class_gwk_1_1_input_1_1_null.html", "class_gwk_1_1_input_1_1_null" ],
        [ "SDL13", "class_gwk_1_1_input_1_1_s_d_l13.html", "class_gwk_1_1_input_1_1_s_d_l13" ],
        [ "SDL2", "class_gwk_1_1_input_1_1_s_d_l2.html", "class_gwk_1_1_input_1_1_s_d_l2" ],
        [ "SFML", "class_gwk_1_1_input_1_1_s_f_m_l.html", "class_gwk_1_1_input_1_1_s_f_m_l" ],
        [ "Windows", "class_gwk_1_1_input_1_1_windows.html", "class_gwk_1_1_input_1_1_windows" ]
      ] ],
      [ "Renderer", null, [
        [ "Allegro", "class_gwk_1_1_renderer_1_1_allegro.html", "class_gwk_1_1_renderer_1_1_allegro" ],
        [ "Base", "class_gwk_1_1_renderer_1_1_base.html", "class_gwk_1_1_renderer_1_1_base" ],
        [ "Direct2D", "class_gwk_1_1_renderer_1_1_direct2_d.html", "class_gwk_1_1_renderer_1_1_direct2_d" ],
        [ "DirectX9", "class_gwk_1_1_renderer_1_1_direct_x9.html", "class_gwk_1_1_renderer_1_1_direct_x9" ],
        [ "GDIPlus", "class_gwk_1_1_renderer_1_1_g_d_i_plus.html", "class_gwk_1_1_renderer_1_1_g_d_i_plus" ],
        [ "GDIPlusBuffered", "class_gwk_1_1_renderer_1_1_g_d_i_plus_buffered.html", "class_gwk_1_1_renderer_1_1_g_d_i_plus_buffered" ],
        [ "ICacheToTexture", "class_gwk_1_1_renderer_1_1_i_cache_to_texture.html", "class_gwk_1_1_renderer_1_1_i_cache_to_texture" ],
        [ "Null", "class_gwk_1_1_renderer_1_1_null.html", "class_gwk_1_1_renderer_1_1_null" ],
        [ "OpenGL", "class_gwk_1_1_renderer_1_1_open_g_l.html", "class_gwk_1_1_renderer_1_1_open_g_l" ],
        [ "OpenGL_DebugFont", "class_gwk_1_1_renderer_1_1_open_g_l___debug_font.html", "class_gwk_1_1_renderer_1_1_open_g_l___debug_font" ],
        [ "SDL2", "class_gwk_1_1_renderer_1_1_s_d_l2.html", "class_gwk_1_1_renderer_1_1_s_d_l2" ],
        [ "SFML2", "class_gwk_1_1_renderer_1_1_s_f_m_l2.html", "class_gwk_1_1_renderer_1_1_s_f_m_l2" ]
      ] ],
      [ "Skin", null, [
        [ "Texturing", null, [
          [ "Bordered", "struct_gwk_1_1_skin_1_1_texturing_1_1_bordered.html", "struct_gwk_1_1_skin_1_1_texturing_1_1_bordered" ],
          [ "Single", "struct_gwk_1_1_skin_1_1_texturing_1_1_single.html", "struct_gwk_1_1_skin_1_1_texturing_1_1_single" ]
        ] ],
        [ "Active_t.Colors.Tab.Active", "struct_gwk_1_1_skin_1_1_base_1_1_tab__t_1_1_active__t_8_colors_8_tab_8_active.html", "struct_gwk_1_1_skin_1_1_base_1_1_tab__t_1_1_active__t_8_colors_8_tab_8_active" ],
        [ "Base", "class_gwk_1_1_skin_1_1_base.html", "class_gwk_1_1_skin_1_1_base" ],
        [ "Base.Colors", "struct_gwk_1_1_skin_1_1_base_8_colors.html", "struct_gwk_1_1_skin_1_1_base_8_colors" ],
        [ "Button_t.Colors.Button", "struct_gwk_1_1_skin_1_1_base_1_1_button__t_8_colors_8_button.html", "struct_gwk_1_1_skin_1_1_base_1_1_button__t_8_colors_8_button" ],
        [ "Category_t.Colors.Category", "struct_gwk_1_1_skin_1_1_base_1_1_category__t_8_colors_8_category.html", "struct_gwk_1_1_skin_1_1_base_1_1_category__t_8_colors_8_category" ],
        [ "Inactive_t.Colors.Tab.Inactive", "struct_gwk_1_1_skin_1_1_base_1_1_tab__t_1_1_inactive__t_8_colors_8_tab_8_inactive.html", "struct_gwk_1_1_skin_1_1_base_1_1_tab__t_1_1_inactive__t_8_colors_8_tab_8_inactive" ],
        [ "Label_t.Colors.Label", "struct_gwk_1_1_skin_1_1_base_1_1_label__t_8_colors_8_label.html", "struct_gwk_1_1_skin_1_1_base_1_1_label__t_8_colors_8_label" ],
        [ "Line_t.Colors.Category.Line", "struct_gwk_1_1_skin_1_1_base_1_1_category__t_1_1_line__t_8_colors_8_category_8_line.html", "struct_gwk_1_1_skin_1_1_base_1_1_category__t_1_1_line__t_8_colors_8_category_8_line" ],
        [ "LineAlt_t.Colors.Category.LineAlt", "struct_gwk_1_1_skin_1_1_base_1_1_category__t_1_1_line_alt__t_8_colors_8_category_8_line_alt.html", "struct_gwk_1_1_skin_1_1_base_1_1_category__t_1_1_line_alt__t_8_colors_8_category_8_line_alt" ],
        [ "Properties_t.Colors.Properties", "struct_gwk_1_1_skin_1_1_base_1_1_properties__t_8_colors_8_properties.html", "struct_gwk_1_1_skin_1_1_base_1_1_properties__t_8_colors_8_properties" ],
        [ "Simple", "class_gwk_1_1_skin_1_1_simple.html", "class_gwk_1_1_skin_1_1_simple" ],
        [ "Tab_t.Colors.Tab", "struct_gwk_1_1_skin_1_1_base_1_1_tab__t_8_colors_8_tab.html", "struct_gwk_1_1_skin_1_1_base_1_1_tab__t_8_colors_8_tab" ],
        [ "TexturedBase", "class_gwk_1_1_skin_1_1_textured_base.html", "class_gwk_1_1_skin_1_1_textured_base" ],
        [ "Tree_t.Colors.Tree", "struct_gwk_1_1_skin_1_1_base_1_1_tree__t_8_colors_8_tree.html", "struct_gwk_1_1_skin_1_1_base_1_1_tree__t_8_colors_8_tree" ],
        [ "Window_t.Colors.Window", "struct_gwk_1_1_skin_1_1_base_1_1_window__t_8_colors_8_window.html", "struct_gwk_1_1_skin_1_1_base_1_1_window__t_8_colors_8_window" ]
      ] ],
      [ "Color", "struct_gwk_1_1_color.html", "struct_gwk_1_1_color" ],
      [ "ControlList", "class_gwk_1_1_control_list.html", "class_gwk_1_1_control_list" ],
      [ "Font", "struct_gwk_1_1_font.html", "struct_gwk_1_1_font" ],
      [ "HSV", "struct_gwk_1_1_h_s_v.html", "struct_gwk_1_1_h_s_v" ],
      [ "IInputEventListener", "class_gwk_1_1_i_input_event_listener.html", "class_gwk_1_1_i_input_event_listener" ],
      [ "Margin", "struct_gwk_1_1_margin.html", "struct_gwk_1_1_margin" ],
      [ "Point", "struct_gwk_1_1_point.html", "struct_gwk_1_1_point" ],
      [ "Rect", "struct_gwk_1_1_rect.html", "struct_gwk_1_1_rect" ],
      [ "TEasyList", "class_gwk_1_1_t_easy_list.html", "class_gwk_1_1_t_easy_list" ],
      [ "Texture", "struct_gwk_1_1_texture.html", "struct_gwk_1_1_texture" ],
      [ "UserDataStorage", "class_gwk_1_1_user_data_storage.html", "class_gwk_1_1_user_data_storage" ],
      [ "WindowProvider", "class_gwk_1_1_window_provider.html", "class_gwk_1_1_window_provider" ]
    ] ],
    [ "TestAPI", "class_test_a_p_i.html", "class_test_a_p_i" ],
    [ "TestCategory", "class_test_category.html", "class_test_category" ],
    [ "TestFrame", "class_test_frame.html", "class_test_frame" ],
    [ "TestUnit", "class_test_unit.html", "class_test_unit" ]
];